"""Inline shared/copy.json into workers/telegram/copy.js for Wrangler.

Run from repo root: python workers/telegram/sync_copy.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "shared" / "copy.json"
DST = Path(__file__).resolve().parent / "copy.js"


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    body = json.dumps(data, ensure_ascii=False, indent=2)
    DST.write_text(
        "// AUTO-GENERATED by sync_copy.py — do not edit.\n"
        "// Source: shared/copy.json\n"
        f"export default {body};\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {DST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
