name = "ipo-devta-bot"
main = "worker.js"
compatibility_date = "2026-09-01"

[[kv_namespaces]]
binding = "PREFS"
id = "44fd223f49a64286baf31fea04e33218"
preview_id = "44fd223f49a64286baf31fea04e33218"

# Set secrets via:
#   wrangler secret put TELEGRAM_TOKEN
#   wrangler secret put CHANNEL_ID
#   wrangler secret put WEBHOOK_SECRET
#   wrangler secret put EXPORT_SECRET
#   wrangler secret put GITHUB_TOKEN
#   wrangler secret put GITHUB_REPO
